/** 선(stroke/line) 위주 아이콘 세트 */
export const outlinePrefixes = [
  'mdi-light',
  'line-md',
  'tabler',
  'mynaui',
  'iconamoon',
  'iconoir',
  'lucide',
  'lucide-lab',
  'uil',
  'uim',
  'uit',
  'gg',
  'flowbite',
  'basil',
  'pixelarticons',
  'pixel',
  'akar-icons',
  'ci',
  'proicons',
  'typcn',
  'meteor-icons',
  'prime',
  'circum',
  'fe',
  'eos-icons',
  'bitcoin-icons',
  'humbleicons',
  'gridicons',
  'mono-icons',
  'cuida',
  'weui',
  'hugeicons',
  'lets-icons',
  'mage',
  'stash',
  'lineicons',
  'icon-park-outline',
  'guidance',
  'carbon',
  'ion',
  'famicons',
  'lsicon',
  'gravity-ui',
  'cil',
  'roentgen',
  'ep',
  'charm',
  'quill',
  'bytesize',
  'rivet-icons',
  'nimbus',
  'formkit',
  'teenyicons',
  'ix',
  'octicon',
  'memory',
  'system-uicons',
  'radix-icons',
  'zondicons',
  'uiw',
  'codex',
  'ei',
  'sidekickicons',
  'pepicons-print',
  'pepicons-pencil',
  'f7',
  'pajamas',
  'garden',
  'fa7-regular',
  'picon',
  'ooui',
  'maki',
  'temaki',
  'oui',
  'nrk',
  'dinkie-icons',
  'qlementine-icons',
  'codicon',
  'nonicons',
  'meteocons'
] as const

/** 채움(fill/solid) 위주 아이콘 세트 */
export const solidPrefixes = [
  'bxs',
  'uis',
  'icon-park-solid',
  'streamline-ultimate',
  'streamline-plump',
  'streamline-sharp',
  'streamline-cyber',
  'streamline-pixel',
  'streamline-block',
  'streamline-freehand',
  'streamline',
  'streamline-flex',
  'fa7-solid',
  'streamline-ultimate-color',
  'streamline-plump-color',
  'streamline-freehand-color',
  'streamline-kameleon-color',
  'streamline-stickies-color',
  'streamline-color',
  'streamline-flex-color',
  'streamline-sharp-color',
  'streamline-cyber-color',
  'game-icons',
  'fad',
  'academicons'
] as const

/** 같은 세트 안에 solid/outline variant가 함께 있는 세트 */
export const mixedPrefixes = [
  'material-symbols',
  'material-symbols-light',
  'ic',
  'mdi',
  'solar',
  'mingcute',
  'ri',
  'tdesign',
  'si',
  'bx',
  'majesticons',
  'duo-icons',
  'icon-park-twotone',
  'jam',
  'ant-design',
  'bi',
  'fluent',
  'ph',
  'clarity',
  'heroicons',
  'pepicons-pop',
  'icon-park',
  'marketeq',
  'wi',
  'healthicons',
  'medical-icon',
  'covid'
] as const

/** 이모지, 로고, 브랜드, 국기 등 UI solid/outline 구분 대상이 아닌 세트 */
export const otherPrefixes = [
  'svg-spinners',
  'fluent-color',
  'vscode-icons',
  'material-icon-theme',
  'file-icons',
  'devicon',
  'devicon-plain',
  'catppuccin',
  'skill-icons',
  'unjs',
  'simple-icons',
  'logos',
  'streamline-logos',
  'cib',
  'fa7-brands',
  'bxl',
  'arcticons',
  'cbi',
  'brandico',
  'entypo-social',
  'token',
  'token-branded',
  'cryptocurrency',
  'cryptocurrency-color',
  'openmoji',
  'twemoji',
  'noto',
  'fluent-emoji-flat',
  'fluent-emoji-high-contrast',
  'noto-v1',
  'emojione',
  'emojione-monotone',
  'emojione-v1',
  'fxemoji',
  'streamline-emojis',
  'circle-flags',
  'flag',
  'flagpack',
  'cif',
  'gis',
  'map',
  'geo'
] as const

const list1 = [
  ...outlinePrefixes, // 외곽선
  // ...solidPrefixes, // 채움
  ...mixedPrefixes, // 외곽선+채움
  ...otherPrefixes
]

const list2 = [
  'openmoji', // 그림이 너무 난잡함.
  'twemoji', // 그림이 너무 난잡함.

  //

  'noto',
  'fluent-emoji-flat',
  'fluent-emoji-high-contrast',
  'noto-v1',
  'emojione',
  'emojione-monotone',
  'emojione-v1',
  'fxemoji',
  'streamline-emojis'
]

export default list1.filter(prefix => !list2.some(p => p == prefix))
